export interface Animation {
  name: string;
  category: 'entrance' | 'exit' | 'attention' | 'special' | 'shadow';
  value: string;
  description: string;
  examples: string[];
  gradient: string;
  content?: string;
}

export const animations: Animation[] = [
  // ENTRANCE ANIMATIONS
  {
    name: 'Fade In',
    category: 'entrance',
    value: 'fadeIn',
    description: 'Gradually appear from transparent.',
    examples: ['fadeIn', "fadeIn({ x: '-100%', y: '100%', opacity: 0 })"],
    gradient: 'from-orange-400 to-teal-600',
  },
  {
    name: 'Slide In',
    category: 'entrance',
    value: "slideIn({ x: '-100%' })",
    description: 'Slide in with optional rotation.',
    examples: ["slideIn({ x: '-100%' })", "slideIn({ y: '100%', scaleY: 0 })", "slideIn({ x: '-100%', rotate: -180 })"],
    gradient: 'from-amber-200 to-amber-400',
    content: '<div class="w-16 h-24 bg-amber-600 rounded-lg transform -rotate-12"></div>',
  },
  {
    name: 'Zoom In',
    category: 'entrance',
    value: 'zoomIn()',
    description: 'Zoom in with optional rotation.',
    examples: ['zoomIn', 'zoomIn({ scale: 0, rotate: 180 })', "zoomIn({ y: '-100%', scale: 0 })"],
    gradient: 'from-slate-100 to-slate-300',
    content: '<div class="w-32 h-32 rounded-full bg-gradient-to-r from-red-400 via-yellow-400 to-purple-400"></div>',
  },
  {
    name: 'Bounce In',
    category: 'entrance',
    value: 'bounceIn',
    description: 'Bounce in with elastic effect.',
    examples: ['bounceIn', 'bounceIn({ scale: 0, opacity: 0 })'],
    gradient: 'from-blue-300 to-blue-500',
    content: '<div class="w-24 h-24 rounded-full bg-white"></div>',
  },
  {
    name: 'Flip In',
    category: 'entrance',
    value: 'flipIn',
    description: 'Flip in with customizable axis.',
    examples: ['flipIn', "flipIn({ axis: 'x', degrees: 90 })", "flipIn({ axis: 'y', degrees: 180 })"],
    gradient: 'from-green-300 to-yellow-500',
    content: '<div class="w-28 h-28 bg-green-700 rounded-lg"></div>',
  },
  {
    name: 'Rotate In',
    category: 'entrance',
    value: 'rotateIn',
    description: 'Rotate in with fade.',
    examples: ['rotateIn', 'rotateIn({ rotate: -180, opacity: 0 })'],
    gradient: 'from-red-400 to-red-600',
    content: '<div class="w-28 h-28 bg-red-800 rounded-xl transform rotate-45"></div>',
  },
  {
    name: 'Light Speed In',
    category: 'entrance',
    value: 'lightSpeedIn',
    description: 'Fast entrance with skew.',
    examples: ['lightSpeedIn', "lightSpeedIn({ distance: '-100%', skew: -30, opacity: 0 })"],
    gradient: 'from-purple-300 to-purple-600',
  },
  {
    name: 'Roll In',
    category: 'entrance',
    value: 'rollIn',
    description: 'Roll in from the side.',
    examples: ['rollIn', "rollIn({ x: '-100%', rotate: -360, opacity: 0 })"],
    gradient: 'from-pink-300 to-pink-600',
    content: '<div class="w-24 h-24 rounded-full bg-pink-800"></div>',
  },
  {
    name: 'Big Entrance',
    category: 'entrance',
    value: 'bigEntrance',
    description: 'Dramatic spinning entrance.',
    examples: ['bigEntrance', 'bigEntrance({ scale: 0, rotate: 720, opacity: 0 })'],
    gradient: 'from-red-500 to-yellow-500',
  },
  {
    name: 'Hatch',
    category: 'entrance',
    value: 'hatch',
    description: 'Emerge with rotation.',
    examples: ['hatch', 'hatch({ scale: 0, rotate: -180, opacity: 0 })'],
    gradient: 'from-purple-400 to-pink-600',
    content: '<div class="w-24 h-32 bg-purple-800 rounded-full"></div>',
  },
  {
    name: 'Bounce In Down',
    category: 'entrance',
    value: 'bounceInDown',
    description: 'Bounce in from top.',
    examples: ['bounceInDown', "bounceInDown({ y: '-100%', opacity: 0 })"],
    gradient: 'from-blue-400 to-cyan-600',
  },
  {
    name: 'Bounce In Up',
    category: 'entrance',
    value: 'bounceInUp',
    description: 'Bounce in from bottom.',
    examples: ['bounceInUp', "bounceInUp({ y: '100%', opacity: 0 })"],
    gradient: 'from-green-400 to-teal-600',
  },
  {
    name: 'Bounce In Left',
    category: 'entrance',
    value: 'bounceInLeft',
    description: 'Bounce in from left.',
    examples: ['bounceInLeft', "bounceInLeft({ x: '-100%', opacity: 0 })"],
    gradient: 'from-yellow-400 to-orange-600',
  },
  {
    name: 'Bounce In Right',
    category: 'entrance',
    value: 'bounceInRight',
    description: 'Bounce in from right.',
    examples: ['bounceInRight', "bounceInRight({ x: '100%', opacity: 0 })"],
    gradient: 'from-pink-400 to-red-600',
  },

  // EXIT ANIMATIONS
  {
    name: 'Fade Out',
    category: 'exit',
    value: 'fadeOut',
    description: 'Gradually disappear to transparent.',
    examples: ['fadeOut', "fadeOut({ x: '100%', y: '-100%', opacity: 0 })"],
    gradient: 'from-slate-400 to-slate-600',
  },
  {
    name: 'Slide Out',
    category: 'exit',
    value: "slideOut({ x: '100%' })",
    description: 'Slide out in any direction.',
    examples: ["slideOut({ x: '100%' })", "slideOut({ x: '0', y: '-100%', opacity: 0 })"],
    gradient: 'from-gray-300 to-gray-500',
  },
  {
    name: 'Zoom Out',
    category: 'exit',
    value: 'zoomOut',
    description: 'Zoom out to smaller size.',
    examples: ['zoomOut', 'zoomOut({ scale: 0, opacity: 0 })'],
    gradient: 'from-zinc-300 to-zinc-600',
  },
  {
    name: 'Bounce Out',
    category: 'exit',
    value: 'bounceOut',
    description: 'Bounce out with elastic effect.',
    examples: ['bounceOut', 'bounceOut({ scale: 0, opacity: 0 })'],
    gradient: 'from-neutral-300 to-neutral-600',
  },
  {
    name: 'Flip Out',
    category: 'exit',
    value: 'flipOut',
    description: 'Flip out with customizable axis.',
    examples: ['flipOut', "flipOut({ axis: 'x', degrees: 90 })", "flipOut({ axis: 'y', degrees: -90 })"],
    gradient: 'from-stone-300 to-red-500',
  },
  {
    name: 'Rotate Out',
    category: 'exit',
    value: 'rotateOut',
    description: 'Rotate out with fade.',
    examples: ['rotateOut', 'rotateOut({ rotate: 180, opacity: 0 })'],
    gradient: 'from-orange-300 to-orange-500',
  },
  {
    name: 'Light Speed Out',
    category: 'exit',
    value: 'lightSpeedOut',
    description: 'Fast exit with skew.',
    examples: ['lightSpeedOut', "lightSpeedOut({ distance: '100%', skew: 30, opacity: 0 })"],
    gradient: 'from-amber-300 to-amber-500',
  },
  {
    name: 'Roll Out',
    category: 'exit',
    value: 'rollOut',
    description: 'Roll out to the side.',
    examples: ['rollOut', "rollOut({ x: '100%', rotate: 360, opacity: 0 })"],
    gradient: 'from-yellow-300 to-yellow-500',
  },
  {
    name: 'Zoom Out Down',
    category: 'exit',
    value: 'zoomOutDown',
    description: 'Zoom out downward.',
    examples: ['zoomOutDown', "zoomOutDown({ y: '100%', scale: 0, opacity: 0 })"],
    gradient: 'from-emerald-300 to-emerald-500',
  },
  {
    name: 'Zoom Out Up',
    category: 'exit',
    value: 'zoomOutUp',
    description: 'Zoom out upward.',
    examples: ['zoomOutUp', "zoomOutUp({ y: '-100%', scale: 0, opacity: 0 })"],
    gradient: 'from-teal-300 to-teal-500',
  },
  {
    name: 'Zoom Out Left',
    category: 'exit',
    value: 'zoomOutLeft',
    description: 'Zoom out to the left.',
    examples: ['zoomOutLeft', "zoomOutLeft({ x: '-100%', scale: 0, opacity: 0 })"],
    gradient: 'from-cyan-300 to-cyan-500',
  },
  {
    name: 'Zoom Out Right',
    category: 'exit',
    value: 'zoomOutRight',
    description: 'Zoom out to the right.',
    examples: ['zoomOutRight', "zoomOutRight({ x: '100%', scale: 0, opacity: 0 })"],
    gradient: 'from-sky-300 to-sky-500',
  },
  {
    name: 'Bounce Out Down',
    category: 'exit',
    value: 'bounceOutDown',
    description: 'Bounce out downward.',
    examples: ['bounceOutDown', "bounceOutDown({ y: '100%', opacity: 0 })"],
    gradient: 'from-blue-300 to-blue-500',
  },
  {
    name: 'Bounce Out Up',
    category: 'exit',
    value: 'bounceOutUp',
    description: 'Bounce out upward.',
    examples: ['bounceOutUp', "bounceOutUp({ y: '-100%', opacity: 0 })"],
    gradient: 'from-indigo-300 to-indigo-500',
  },
  {
    name: 'Bounce Out Left',
    category: 'exit',
    value: 'bounceOutLeft',
    description: 'Bounce out to the left.',
    examples: ['bounceOutLeft', "bounceOutLeft({ x: '-100%', opacity: 0 })"],
    gradient: 'from-violet-300 to-violet-500',
  },
  {
    name: 'Bounce Out Right',
    category: 'exit',
    value: 'bounceOutRight',
    description: 'Bounce out to the right.',
    examples: ['bounceOutRight', "bounceOutRight({ x: '100%', opacity: 0 })"],
    gradient: 'from-purple-300 to-purple-500',
  },

  // ATTENTION SEEKERS
  {
    name: 'Pulse',
    category: 'attention',
    value: 'pulse',
    description: 'Pulsing scale with optional fade.',
    examples: ['pulse', 'pulse({ scale1: 1.2 })', 'pulse({ opacity: 0 })'],
    gradient: 'from-pink-400 to-rose-600',
  },
  {
    name: 'Shake',
    category: 'attention',
    value: 'shake',
    description: 'Horizontal shake effect.',
    examples: ['shake', "shake({ x1: '-10px', x2: '10px' })"],
    gradient: 'from-red-400 to-orange-600',
  },
  {
    name: 'Swing',
    category: 'attention',
    value: 'swing',
    description: 'Pendulum swing effect.',
    examples: ['swing', 'swing({ rotate1: 15, rotate2: -15 })'],
    gradient: 'from-orange-400 to-yellow-600',
  },
  {
    name: 'Tada',
    category: 'attention',
    value: 'tada',
    description: 'Celebratory shake and scale.',
    examples: ['tada', 'tada({ scale: 1.1, rotate: 3 })'],
    gradient: 'from-yellow-400 to-lime-600',
  },
  {
    name: 'Wobble',
    category: 'attention',
    value: 'wobble',
    description: 'Wobble with optional skew.',
    examples: ['wobble', 'wobble({ rotate1: -10, rotate2: 8 })', 'wobble({ skewX1: -10, skewX2: 10 })'],
    gradient: 'from-lime-400 to-green-600',
  },
  {
    name: 'Jello',
    category: 'attention',
    value: 'jello',
    description: 'Jello-like wobble effect.',
    examples: ['jello', 'jello({ skewX1: -12.5, skewX2: 6.25, skewY1: -12.5, skewY2: 6.25 })'],
    gradient: 'from-green-400 to-emerald-600',
  },
  {
    name: 'Heart Beat',
    category: 'attention',
    value: 'heartBeat',
    description: 'Heart beating effect.',
    examples: ['heartBeat', 'heartBeat({ scale: 1.3 })'],
    gradient: 'from-red-400 to-pink-600',
    content: '<div class="text-6xl">❤️</div>',
  },
  {
    name: 'Rubber Band',
    category: 'attention',
    value: 'rubberBand',
    description: 'Rubber band stretch effect.',
    examples: ['rubberBand', 'rubberBand({ scaleX: 1.25, scaleY: 0.75 })'],
    gradient: 'from-emerald-400 to-teal-600',
  },
  {
    name: 'Flash',
    category: 'attention',
    value: 'flash',
    description: 'Flashing opacity effect.',
    examples: ['flash', 'flash({ opacity: 0 })'],
    gradient: 'from-yellow-300 to-yellow-500',
  },
  {
    name: 'Head Shake',
    category: 'attention',
    value: 'headShake',
    description: '"No" head shake motion.',
    examples: ['headShake', 'headShake({ x1: -10, x2: 10, rotateY1: -10, rotateY2: 10 })'],
    gradient: 'from-teal-400 to-cyan-600',
  },
  {
    name: 'Blur',
    category: 'attention',
    value: 'blur',
    description: 'Blur to focus effect.',
    examples: ['blur', "blur({ blur1: '10px', blur2: '0px', opacity: 0 })"],
    gradient: 'from-cyan-400 to-blue-600',
  },
  {
    name: 'Ken Burns',
    category: 'attention',
    value: 'kenBurns',
    description: 'Slow zoom and pan for images.',
    examples: ['kenBurns', "kenBurns({ scale: 1.2, x: '10%', y: '10%' })"],
    gradient: 'from-blue-400 to-indigo-600',
  },
  {
    name: 'Bounce',
    category: 'attention',
    value: 'bounce',
    description: 'Bounce with customizable direction.',
    examples: ['bounce', "bounce({ y1: '-30px' })", "bounce({ x1: '20px', y1: '0' })"],
    gradient: 'from-indigo-400 to-purple-600',
  },
  {
    name: 'Rotational Wave',
    category: 'attention',
    value: 'rotationalWave',
    description: 'Continuous rotation wave.',
    examples: ['rotationalWave', 'rotationalWave({ rotate1: 15, rotate2: -15 })'],
    gradient: 'from-purple-400 to-fuchsia-600',
  },
  {
    name: 'Impulse Rotation',
    category: 'attention',
    value: 'impulseRotation',
    description: 'Impulse rotation with direction.',
    examples: ['impulseRotation', "impulseRotation({ direction: 'left' })", 'impulseRotation({ rotate1: 15 })'],
    gradient: 'from-fuchsia-400 to-rose-600',
  },
  {
    name: 'Tossing',
    category: 'attention',
    value: 'tossing',
    description: 'Rotation with vertical movement.',
    examples: ['tossing', "tossing({ rotate1: -10, rotate2: 10, y1: '-5px', y2: '5px' })"],
    gradient: 'from-rose-400 to-red-600',
  },
  {
    name: 'Pull Up',
    category: 'attention',
    value: 'pullUp',
    description: 'Pull up and down motion.',
    examples: ['pullUp', "pullUp({ y: '-10px' })"],
    gradient: 'from-red-400 to-orange-500',
  },
  {
    name: 'Pull Down',
    category: 'attention',
    value: 'pullDown',
    description: 'Pull down and up motion.',
    examples: ['pullDown', "pullDown({ y: '10px' })"],
    gradient: 'from-orange-400 to-amber-500',
  },
  {
    name: 'Glow',
    category: 'attention',
    value: 'glow',
    description: 'Glow effect animation.',
    examples: ['glow', "glow({ boxShadow: '0 0 20px rgba(255, 255, 255, 0.8)' })"],
    gradient: 'from-amber-400 to-yellow-500',
  },
  {
    name: 'Shadow',
    category: 'attention',
    value: 'shadow',
    description: 'Shadow effect animation.',
    examples: ['shadow', "shadow({ boxShadow: '0 10px 20px rgba(0, 0, 0, 0.3)' })"],
    gradient: 'from-yellow-400 to-lime-500',
  },
  {
    name: 'Grow Shadow',
    category: 'attention',
    value: 'growShadow',
    description: 'Grow with shadow effect.',
    examples: ['growShadow', "growShadow({ scale: 1.1, boxShadow: '0 10px 30px rgba(0, 0, 0, 0.4)' })"],
    gradient: 'from-lime-400 to-green-500',
  },
  {
    name: 'Float Shadow',
    category: 'attention',
    value: 'floatShadow',
    description: 'Float with shadow effect.',
    examples: ['floatShadow', "floatShadow({ y: '-10px', boxShadow: '0 15px 30px rgba(0, 0, 0, 0.3)' })"],
    gradient: 'from-green-400 to-emerald-500',
  },
  {
    name: 'Bob',
    category: 'attention',
    value: 'bob',
    description: 'Bobbing up and down.',
    examples: ['bob', "bob({ y1: '-10px', y2: '0px' })"],
    gradient: 'from-emerald-400 to-teal-500',
  },
  {
    name: 'Hang',
    category: 'attention',
    value: 'hang',
    description: 'Hanging swing effect.',
    examples: ['hang', 'hang({ rotate1: 10, rotate2: -10 })'],
    gradient: 'from-teal-400 to-cyan-500',
  },

  // SPECIAL EFFECTS
  {
    name: 'Glitch',
    category: 'special',
    value: 'glitch',
    description: 'Digital glitch effect.',
    examples: ['glitch', 'glitch({ x1: \'-5px\', x2: \'5px\' })'],
    gradient: 'from-red-500 to-blue-500',
  },
  {
    name: 'Spin',
    category: 'special',
    value: 'spin',
    description: 'Complete 360° rotation.',
    examples: ['spin', 'spin({ degrees: 720 })', 'spin({ degrees: -360 })'],
    gradient: 'from-purple-500 to-pink-500',
  },
  {
    name: 'Flip',
    category: 'special',
    value: 'flip',
    description: 'Continuous flip animation.',
    examples: ['flip', 'flip({ axis: \'x\' })', 'flip({ rotate1: 90, rotate2: 180 })'],
    gradient: 'from-indigo-500 to-purple-500',
  },
  {
    name: 'Blur',
    category: 'special',
    value: 'blur',
    description: 'Blur to focus effect.',
    examples: ['blur', 'blur({ blur1: \'20px\' })', 'blur({ blur2: \'5px\' })'],
    gradient: 'from-cyan-500 to-blue-500',
  },
  {
    name: 'Ken Burns',
    category: 'special',
    value: 'kenBurns',
    description: 'Cinematic zoom and pan effect.',
    examples: ['kenBurns', 'kenBurns({ scale: 1.3, x: \'10%\', y: \'10%\' })'],
    gradient: 'from-blue-500 to-indigo-500',
  },
  {
    name: 'Morphing',
    category: 'special',
    value: 'morphing',
    description: 'Shape transformation effect.',
    examples: ['morphing', 'morphing({ scale1: 1.5, rotate: 90 })'],
    gradient: 'from-violet-500 to-fuchsia-500',
  },
  {
    name: 'Skew',
    category: 'special',
    value: 'skew',
    description: 'Skew/tilt transformation.',
    examples: ['skew', 'skew({ skewX: -20, skewY: -20 })'],
    gradient: 'from-fuchsia-500 to-pink-500',
  },
  {
    name: 'Squeeze',
    category: 'special',
    value: 'squeeze',
    description: 'Alternating compression effect.',
    examples: ['squeeze', 'squeeze({ scaleX1: 1.5, scaleY1: 0.5 })'],
    gradient: 'from-rose-500 to-red-500',
  },

  // SHADOW EFFECTS
  {
    name: 'Glow',
    category: 'shadow',
    value: 'glow',
    description: 'Glowing light effect.',
    examples: ['glow', 'glow({ boxShadow: \'0 0 30px rgba(0, 255, 255, 1)\' })'],
    gradient: 'from-yellow-400 to-amber-500',
  },
  {
    name: 'Shadow',
    category: 'shadow',
    value: 'shadow',
    description: 'Drop shadow effect.',
    examples: ['shadow', 'shadow({ boxShadow: \'0 15px 30px rgba(0, 0, 0, 0.5)\' })'],
    gradient: 'from-gray-600 to-gray-800',
  },
  {
    name: 'Grow Shadow',
    category: 'shadow',
    value: 'growShadow',
    description: 'Grow with shadow effect.',
    examples: ['growShadow', 'growShadow({ scale: 1.2 })'],
    gradient: 'from-slate-500 to-zinc-700',
  },
  {
    name: 'Float Shadow',
    category: 'shadow',
    value: 'floatShadow',
    description: 'Float with shadow effect.',
    examples: ['floatShadow', 'floatShadow({ y: \'-20px\' })'],
    gradient: 'from-stone-500 to-neutral-700',
  },
];
